spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db # PostgreSQL URL, mydatabase를 실제 데이터베이스 이름으로 변경
    username: postgres # PostgreSQL 사용자 이름
    password: 1234 # PostgreSQL 사용자 비밀번호
    driver-class-name: org.postgresql.Driver # PostgreSQL 드라이버 클래스

  jpa:
    hibernate:
      ddl-auto: create # 테이블 자동 생성 (운영 환경에서는 'none' 또는 'validate' 추천)
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect # PostgreSQL에 맞는 Hibernate dialect
        format_sql: true # SQL을 보기 쉽게 출력

  # H2 Console 비활성화
#  h2:
#    console:
#      enabled: false

openai:
  secret-key: ${OPENAI_SECRET_KEY}
  organization-id: ${OPENAI_ORGANIZATION_ID}

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 62e10d29b8acb986b74f1db20a5e86d4
            client-secret: D7WISaxfuqxMvI6vdvzbD2WJeAGKBUkX
            redirect-uri: "http://localhost:8080/login/oauth2/code/kakao"
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            client-name: Kakao
            scope:
              - profile_nickname
              - profile_image
              - account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

logging:
  level:
    org.hibernate.SQL: debug

jwt:
  expiration-time: 86400000